{{- if and .Values.mongodb.enabled .Values.mongodb.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "collectibles-tracker-chart.fullname" . }}-mongodb-pvc
  labels:
    {{- include "collectibles-tracker-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: mongodb
spec:
  accessModes:
    - {{ .Values.mongodb.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.mongodb.persistence.size }}
  {{- if .Values.mongodb.persistence.storageClass }}
  {{- if (eq "-" .Values.mongodb.persistence.storageClass) }}
  storageClassName: ""
  {{- else }}
  storageClassName: {{ .Values.mongodb.persistence.storageClass }}
  {{- end }}
  {{- end }}
{{- end }}
