{{- if .Values.mongodb.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "collectibles-tracker-chart.fullname" . }}-mongodb
  labels:
    {{- include "collectibles-tracker-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "collectibles-tracker-chart.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: mongodb
  template:
    metadata:
      labels:
        {{- include "collectibles-tracker-chart.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: mongodb
    spec:
      containers:
        - name: mongodb
          image: "{{ .Values.mongodb.image.repository }}:{{ .Values.mongodb.image.tag }}"
          imagePullPolicy: {{ .Values.mongodb.image.pullPolicy }}
          ports:
            - name: mongodb
              containerPort: 27017
              protocol: TCP
          env:
            - name: MONGO_INITDB_DATABASE
              value: {{ .Values.mongodb.env.MONGO_INITDB_DATABASE | quote }}
          {{- if .Values.mongodb.healthcheck.enabled }}
          livenessProbe:
            exec:
              command:
                - mongosh
                - --eval
                - "db.adminCommand('ping')"
            initialDelaySeconds: {{ .Values.mongodb.healthcheck.initialDelaySeconds }}
            periodSeconds: {{ .Values.mongodb.healthcheck.periodSeconds }}
            timeoutSeconds: {{ .Values.mongodb.healthcheck.timeoutSeconds }}
            failureThreshold: {{ .Values.mongodb.healthcheck.failureThreshold }}
          readinessProbe:
            exec:
              command:
                - mongosh
                - --eval
                - "db.adminCommand('ping')"
            initialDelaySeconds: {{ .Values.mongodb.healthcheck.initialDelaySeconds }}
            periodSeconds: {{ .Values.mongodb.healthcheck.periodSeconds }}
            timeoutSeconds: {{ .Values.mongodb.healthcheck.timeoutSeconds }}
            failureThreshold: {{ .Values.mongodb.healthcheck.failureThreshold }}
          {{- end }}
          resources:
            {{- toYaml .Values.mongodb.resources | nindent 12 }}
          volumeMounts:
            - name: mongodb-data
              mountPath: /data/db
      volumes:
        - name: mongodb-data
          {{- if .Values.mongodb.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "collectibles-tracker-chart.fullname" . }}-mongodb-pvc
          {{- else }}
          emptyDir: {}
          {{- end }}
{{- end }}
